packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - sharp
  - esbuild
  - "@tailwindcss/oxide"
  - unrs-resolver
allowBuilds:
  "@scarf/scarf": true
  electron: true
  esbuild: true
  sharp: true
  sharp@0.34.5: true
  esbuild@0.18.20: true
  esbuild@0.25.12 : true
  esbuild@0.28.2: true
  unrs-resolver: true
